# This runs infrastructure validation
name: Front-end CI - Infrastructure

# Controls when the action will run. 
on:
  # Do this for all changes on each branch and on PRs into main
  push:
    branches:
      - '**'
    paths:
      - 'front-end/infrastructure/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'front-end/infrastructure/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Synthesize the CDK templates
  test-fresh-deployment:
    name: Fresh Deployment

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Change to infrastructure directory
        run: cd $GITHUB_WORKSPACE/front-end/infrastructure

      - name: Generate Environment Temp Code
        run: export ENVIRONMENT=$(openssl rand -hex 3)

      # Deploy fresh template
      - name: Deploy Template
        uses: youyo/aws-cdk-github-actions@v1
        with:
          cdk_subcommand: 'deploy'
          cdk_version: '1.80.0'
          working_dir: front-end/infrastructure/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
          ENVIRONMENT: $ENVIRONMENT
    
      # Destroy fresh template
      - name: Destroy Template
        uses: youyo/aws-cdk-github-actions@v1
        with:
          cdk_subcommand: 'destroy --force'
          cdk_version: '1.80.0'
          working_dir: front-end/infrastructure/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
          ENVIRONMENT: $ENVIRONMENT